name: Gradle CI

on:
  workflow_call:
    inputs:
      java:
        description: "The version of Java to use to run Gradle" # Note: Gradle's Java toolchains feature is used for compiling, which is separate from this
        required: false
        type: string
        default: "17"
      gradle_tasks:
        description: "The Gradle tasks to run"
        required: false
        type: string
        default: "publish"
      artifact_group:
        description: "Maven group"
        required: false
        type: string
        default: "net.minecraftforge"
      artifact_name:
        description: "Maven artifact"
        required: false
        type: string
        default: "dont promote"
      artifact_version:
        description: "Maven version"
        required: false
        type: string
        default: "???"
      promotion_type:
        description: "Promotion type"
        required: false
        type: string
        default: "latest"
    secrets:
      DISCORD_WEBHOOK:
        required: true
      PROMOTE_ARTIFACT_WEBHOOK:
        required: true
      PROMOTE_ARTIFACT_USERNAME:
        required: true
      PROMOTE_ARTIFACT_PASSWORD:
        required: true
      MAVEN_USER:
        required: true
      MAVEN_PASSWORD:
        required: true

permissions:
  contents: read

jobs:
  notify-discord-start:
    name: Notify Discord (start)
    uses: ForgeGHActionsTestOrg/Actions/.github/workflows/discord_build_notifier.yml@main
    with:
      build_status: started
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true

      - name: Make Gradle executable
        # language=bash
        run: chmod +x ./gradlew

      - name: Setup Java ${{ inputs.java }}
        # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#java
        # language=bash
        run: export JAVA_HOME=$(echo $JAVA_HOME_${{ inputs.java }}_X64)

      - name: Gradle ${{ inputs.gradle_tasks }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ inputs.gradle_tasks }}
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

  notify-discord-end:
    name: Notify Discord (end)
    needs: [ "notify-discord-start", "gradle" ]
    if: ${{ always() }}
    uses: ForgeGHActionsTestOrg/Actions/.github/workflows/discord_build_notifier.yml@main
    with:
      build_status: ${{ needs.gradle.result }}
      build_number: ${{ needs.notify-discord-start.outputs.build_number }}
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

  promote-artifact:
    name: Promote artifact
    needs: [ "notify-discord-start", "gradle" ]
    if: needs.gradle.result == 'success' && inputs.artifact_name != 'dont promote'
    uses: MinecraftForge/SharedActions/.github/workflows/promote_artifact.yml@main
    with:
      group: ${{ inputs.artifact_group }}
      artifact: ${{ inputs.artifact_name }}
      version: ${{ needs.notify-discord-start.outputs.build_number }}
      type: ${{ inputs.promotion_type }}
    secrets:
      PROMOTE_ARTIFACT_WEBHOOK: ${{ secrets.PROMOTE_ARTIFACT_WEBHOOK }}
      PROMOTE_ARTIFACT_USERNAME: ${{ secrets.PROMOTE_ARTIFACT_USERNAME }}
      PROMOTE_ARTIFACT_PASSWORD: ${{ secrets.PROMOTE_ARTIFACT_PASSWORD }}
